# Generated by Django 6.0.3 on 2026-04-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_recentlyviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewed',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
