# Generated by Django 6.0.3 on 2026-04-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_alter_recentlyviewed_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyviewed',
            name='last_viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recentlyviewed',
            name='view_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
