# Generated by Django 6.0.3 on 2026-04-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_address_order_phone_number_orderitem_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
