# Generated by Django 6.0.3 on 2026-04-06 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0004_alter_user_options_company_is_active_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_slug_da4386_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_slug_3edc0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_status_041708_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_ca4d9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='productversion',
            name='products_pr_is_acti_dc947a_idx',
        ),
        migrations.RemoveIndex(
            model_name='productversion',
            name='products_pr_is_feat_ab8c69_idx',
        ),
        migrations.AlterField(
            model_name='productversion',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_active'], name='products_pr_status_c4a457_idx'),
        ),
        migrations.AddIndex(
            model_name='productversion',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_84abb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='unique_main_image_per_product'),
        ),
    ]
