# Generated by Django 6.0.3 on 2026-04-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productversionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
