# Generated by Django 6.0.3 on 2026-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_tax_rate_productversion_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_wishlist',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
