# Generated by Django 6.0.3 on 2026-04-16 06:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_image_alter_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
